title: Asa Putra
email: your-email@example.com
description: >-
  Ini adalah situs pribadi Asa Putra — profesional pelaut dan pembuat proyek kreatif.

twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:name/

include:
  - _posts
