name: Sync Notion Blog to GitHub

on:
  schedule:
    - cron: "*/30 * * * *" # Setiap 30 menit otomatis sync
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Notion Database and Convert to Markdown
        uses: splitbee/notion-blog-to-markdown@main
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.NOTION_DB_ID }}
